version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/copy.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: root