apiVersion: batch/v1
kind: Job
metadata:
  name: notify-email
  namespace: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: email-notifier
        image: alpine:3.20
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache msmtp ca-certificates
          cat <<EOF > /etc/msmtprc
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        /tmp/msmtp.log

          account        gmail
          host           smtp.gmail.com
          port           587
          from           $(cat /secrets/gmail_user)
          user           $(cat /secrets/gmail_user)
          password       $(cat /secrets/gmail_pass)

          account default : gmail
          EOF

          echo -e "Subject: ArgoCD Deployment Success\n\n✅ ArgoCD Sync completed successfully!" | msmtp recipient@example.com
          echo "--- msmtp log ---"
          cat /tmp/msmtp.log
        volumeMounts:
        - name: gmail-secret
          mountPath: /secrets
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: gmail-secret
        secret:
          secretName: gmail-smtp-secret
  backoffLimit: 1
