on: [push]
    
jobs:
  github-action-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Running a shell script that will print the value of environment variables
        run: sh print.sh
        env:
          TEST_HOST: ubuntu-host
          TEST_PORT: 9999
	  TEST_MSG: "Welcome to Github Actions"
